# Interactive Python


## In and Out

Let's  run any code with visible output:

In [1]:
help(vars)

Help on built-in function vars in module builtins:

vars(...)
    vars([object]) -> dictionary
    
    Without arguments, equivalent to locals().
    With an argument, equivalent to object.__dict__.



In [2]:
'In' in vars() and "Out" in vars()

True

In [3]:
type(In)

list

In [4]:
type(Out)

dict

In [5]:
In

['',
 'help(vars)',
 '\'In\' in vars() and "Out" in vars()',
 'type(In)',
 'type(Out)',
 'In']

In [6]:
In[1]

'help(vars)'

In [7]:
Out

{2: True,
 3: list,
 4: dict,
 5: ['',
  'help(vars)',
  '\'In\' in vars() and "Out" in vars()',
  'type(In)',
  'type(Out)',
  'In',
  'In[1]',
  'Out'],
 6: 'help(vars)'}

The Out object is not a list but a dictionary mapping input numbers to their outputs (if any):

In [8]:
Out[3]

list

Some more tips:



Out[N] is _N

In [9]:
_3

list

The easiest way to suppress the output of a command is to add a semicolon to the end of the line

In [10]:
42 ** 42

150130937545296572356771972164254457814047970568738777235893533016064

In [11]:
42 ** 42;

In [12]:
11 in Out

False

In [13]:
In[11]

'42 ** 42;'

In [14]:
_

'42 ** 42;'

In [15]:
__

'42 ** 42;'

In [16]:
___

'42 ** 42;'

In [17]:
_i

'___'

In [18]:
_ii

'___'

In [19]:
_iii

'___'

## Magic Commands

% - line magic - single line of input

%% - cell magic - multiple lines of input

In [20]:
%magic


IPython's 'magic' functions

The magic function system provides a series of functions which allow you to
control the behavior of IPython itself, plus a lot of system-type
features. There are two kinds of magics, line-oriented and cell-oriented.

Line magics are prefixed with the % character and work much like OS
command-line calls: they get as an argument the rest of the line, where
arguments are passed without parentheses or quotes.  For example, this will
time the given statement::

        %timeit range(1000)

Cell magics are prefixed with a double %%, and they are functions that get as
an argument not only the rest of the line, but also the lines below it in a
separate argument.  These magics are called with two arguments: the rest of the
call line and the body of the cell, consisting of the lines below the first.
For example::

        %%timeit x = numpy.random.randn((100, 100))
        numpy.linalg.svd(x)

will time the execution of the numpy svd routine, running the assignment 

In [21]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%

In [22]:
%%writefile?

Docstring:
::

  %writefile [-a] filename

Write the contents of the cell to a file.

The file will be overwritten unless the -a (--append) flag is specified.

positional arguments:
  filename      file to write

optional arguments:
  -a, --append  Append contents of the cell to an existing file. The file will be created if it does not exist.
File:      /opt/homebrew/Caskroom/miniforge/base/envs/env3.8/lib/python3.8/site-packages/IPython/core/magics/osm.py


In [23]:
%%writefile script.py

def hello_printer():
    print('one more hello world')


hello_printer()

Writing script.py


You can run external code with the %run magic:

Automagic is ON, % prefix IS NOT needed for line magics!

In [24]:
run script.py

one more hello world


In [25]:
hello_printer()

one more hello world


In [26]:
%timeit lst = [n ** 2 for n in range(10_000_000)]

2.78 s ± 123 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [27]:
%%timeit

lst = list()
for n in range(10_000_000):
    lst.append(n ** 2)

2.99 s ± 94.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [28]:
history -n 1-4

   1: help(vars)
   2: 'In' in vars() and "Out" in vars()
   3: type(In)
   4: type(Out)


In [ ]:
%timeit lst = [n ** 2 for n in range(1000_000)];

In [ ]:
%timeit lst = [0 for x in range(int(1e6))]

In [ ]:
%timeit?

## Shell Commands

The list of useful commands [here](https://lym.readthedocs.io/en/latest/startingcommands.html)

In [29]:
!pwd                 # print working directory

/Users/isklonin/Projects/01-teaching/ai_masters/2023/lectures/lecture11


In [30]:
!ls                  # list working directory contents

aggregations.png lecture11.ipynb  script.py


In [31]:
!echo "hello world"  # like python's print

hello world


In [32]:
lst = !ls

In [33]:
lst

['aggregations.png', 'lecture11.ipynb', 'script.py']

# Numpy

In [34]:
import numpy as np

## N-dimensional Array

The ``ndarray`` is very useful object of the numpy package.
It adds efficient *operations* for working on data.

In [35]:
import numpy as np

In [36]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [37]:
np.array([3.141592, 4, 2, 3])

array([3.141592, 4.      , 2.      , 3.      ])

In [38]:
arr = np.array([1, 2, 3, 4, 5], dtype='float32')
arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [39]:
np.array([range(5) for _ in range(5)])  # nested lists result in multi-dimensional arrays

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### Creating Arrays


In [40]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
np.full((3, 5), 3.141592)

array([[3.141592, 3.141592, 3.141592, 3.141592, 3.141592],
       [3.141592, 3.141592, 3.141592, 3.141592, 3.141592],
       [3.141592, 3.141592, 3.141592, 3.141592, 3.141592]])

In [43]:
np.arange(0, 20, 2)  # like python range()

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [44]:
np.linspace(-1, 1, 5)

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [45]:
np.random.random((3, 3))

array([[0.23067893, 0.82627746, 0.74713926],
       [0.14961831, 0.80800365, 0.22986489],
       [0.75144638, 0.18097008, 0.59887608]])

In [46]:
np.random.normal(0, 1, (3, 3))

array([[-0.07015707,  0.15641448,  0.68589298],
       [-0.34320362, -0.63905591, -0.11077546],
       [ 1.30032306, -1.49272682,  0.99823761]])

In [47]:
np.random.randint(0, 10, (3, 3))

array([[3, 2, 9],
       [0, 5, 1],
       [6, 5, 8]])

In [48]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
np.empty?

In [50]:
np.empty(7)

array([0., 0., 0., 0., 0., 0., 0.])

### Numpy Data Types


| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 

In [51]:
np.zeros(4, dtype='int32')

array([0, 0, 0, 0], dtype=int32)

In [52]:
np.zeros(4, dtype=np.int32)

array([0, 0, 0, 0], dtype=int32)

For more information [NumPy data types](https://numpy.org/doc/stable/user/basics.types.html#).


### Attributes

In [53]:
def attr_printer(obj):
    print(*[name for name in dir(obj) if not (name.startswith('_') or callable(getattr(obj, name)))], sep='\n')

In [54]:
type(arr)

numpy.ndarray

In [55]:
attr_printer(arr)

T
base
ctypes
data
dtype
flags
flat
imag
itemsize
nbytes
ndim
real
shape
size
strides


In [60]:
np.random.seed(42)                            # seed for reproducibility

arr1 = np.random.randint(10, size=6)          # 1-d array
arr2 = np.random.randint(10, size=(3, 4))     # 2-d array
arr3 = np.random.randint(10, size=(3, 4, 5))  # 3-d array
print(arr1, arr2, arr3, sep='\n`')

[6 3 7 4 6 9]
`[[2 6 7 4]
 [3 7 7 2]
 [5 4 1 7]]
`[[[5 1 4 0 9]
  [5 8 0 9 2]
  [6 3 8 2 4]
  [2 6 4 8 6]]

 [[1 3 8 1 9]
  [8 9 4 1 3]
  [6 7 2 0 3]
  [1 7 3 1 5]]

 [[5 9 3 5 1]
  [9 1 9 3 7]
  [6 8 7 4 1]
  [4 7 9 8 8]]]


In [61]:
arr3.ndim

3

In [62]:
arr3.shape

(3, 4, 5)

In [63]:
arr3.size

60

In [64]:
print(np.random.randint(10, size=6))          # 1-d array
print(np.random.randint(10, size=(3, 4)))     # 2-d array
print(np.random.randint(10, size=(3, 4, 5)))  # 3-d array

[0 8 6 8 7 0]
[[7 7 2 0]
 [7 2 2 0]
 [4 9 6 9]]
[[[8 6 8 7 1]
  [0 6 6 7 4]
  [2 7 5 2 0]
  [2 4 2 0 4]]

 [[9 6 6 8 9]
  [9 2 6 0 3]
  [3 4 6 6 3]
  [6 2 5 1 9]]

 [[8 4 5 3 9]
  [6 8 6 0 0]
  [8 8 3 8 2]
  [6 5 7 8 4]]]


In [65]:
np.random.seed(42)

print(np.random.randint(10, size=6))          # 1-d array
print(np.random.randint(10, size=(3, 4)))     # 2-d array
print(np.random.randint(10, size=(3, 4, 5)))  # 3-d array

[6 3 7 4 6 9]
[[2 6 7 4]
 [3 7 7 2]
 [5 4 1 7]]
[[[5 1 4 0 9]
  [5 8 0 9 2]
  [6 3 8 2 4]
  [2 6 4 8 6]]

 [[1 3 8 1 9]
  [8 9 4 1 3]
  [6 7 2 0 3]
  [1 7 3 1 5]]

 [[5 9 3 5 1]
  [9 1 9 3 7]
  [6 8 7 4 1]
  [4 7 9 8 8]]]


### Accessing Single Elements

In [66]:
arr1

array([6, 3, 7, 4, 6, 9])

In [67]:
arr1[0]

6

In [68]:
arr1[4]

6

In [69]:
arr1[-1]

9

In [70]:
arr1[-2]

6

In [71]:
arr2

array([[2, 6, 7, 4],
       [3, 7, 7, 2],
       [5, 4, 1, 7]])

In [72]:
arr2[0, 0]

2

In [73]:
lst = [[0]]
print(lst[0][0])
lst[0, 0]

0


TypeError: list indices must be integers or slices, not tuple

In [74]:
arr2[2, 0]

5

In [75]:
arr2[2, -1]

7

In [76]:
arr2[0, 0] = 12
arr2

array([[12,  6,  7,  4],
       [ 3,  7,  7,  2],
       [ 5,  4,  1,  7]])

In [77]:
arr2[0] = 3.1415926535  # will be truncated
arr2

array([[3, 3, 3, 3],
       [3, 7, 7, 2],
       [5, 4, 1, 7]])

## Shape Manipulation

### Slicing

Default values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.


In [78]:
arr = np.arange(10)
arr, arr[::-2]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([9, 7, 5, 3, 1]))

### Multi-dimensional

In [79]:
arr2

array([[3, 3, 3, 3],
       [3, 7, 7, 2],
       [5, 4, 1, 7]])

two rows, three columns

In [80]:
arr2[:2, :3]  

array([[3, 3, 3],
       [3, 7, 7]])

In [81]:
arr2[:3, ::2]  

array([[3, 3],
       [3, 7],
       [5, 1]])

In [82]:
arr2[::-1, ::-1]

array([[7, 1, 4, 5],
       [2, 7, 7, 3],
       [3, 3, 3, 3]])

### Accessing array rows and columns


In [83]:
print(arr2[:, 0])  # column of arr2
arr2[:, 0]

[3 3 5]


array([3, 3, 5])

In [84]:
print(arr2[0, :])  # row of arr2

[3 3 3 3]


In [85]:
print(arr2[0])  # equivalent to arr2[0, :]

[3 3 3 3]


### Views


In [86]:
print(arr2)

[[3 3 3 3]
 [3 7 7 2]
 [5 4 1 7]]


In [87]:
arr2_sub = arr2[:2, :2]
print(arr2_sub)

[[3 3]
 [3 7]]


In [88]:
arr2_sub[1, 1] = 42
print(arr2_sub)

[[ 3  3]
 [ 3 42]]


In [89]:
print(arr2)

[[ 3  3  3  3]
 [ 3 42  7  2]
 [ 5  4  1  7]]


### Copies

This can be done with the ``copy()`` method:

In [90]:
arr2_sub_copy = arr2[:2, :2].copy()
print(arr2_sub_copy)

[[ 3  3]
 [ 3 42]]


In [91]:
arr2_sub_copy[0, 0] = 42
print(arr2_sub_copy)

[[42  3]
 [ 3 42]]


In [92]:
print(arr2)

[[ 3  3  3  3]
 [ 3 42  7  2]
 [ 5  4  1  7]]


### Reshaping

In [93]:
def methods_printer(obj):
    print(len([name for name in dir(obj) if not ((name.startswith('_') or not callable(getattr(obj, name))))]))
    print(*[name for name in dir(obj) if not ((name.startswith('_') or not callable(getattr(obj, name))))], sep='\n')

In [94]:
methods_printer(arr)

56
all
any
argmax
argmin
argpartition
argsort
astype
byteswap
choose
clip
compress
conj
conjugate
copy
cumprod
cumsum
diagonal
dot
dump
dumps
fill
flatten
getfield
item
itemset
max
mean
min
newbyteorder
nonzero
partition
prod
ptp
put
ravel
repeat
reshape
resize
round
searchsorted
setfield
setflags
sort
squeeze
std
sum
swapaxes
take
tobytes
tofile
tolist
tostring
trace
transpose
var
view


In [95]:
np.arange(42)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41])

In [96]:
grid = np.arange(42).reshape((6, 7))
print(grid)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]


In [97]:
arr = np.array([1, 2, 3, 4, 5])

arr.reshape((1, 5)).ndim

2

row vector via newaxis

In [98]:
arr

array([1, 2, 3, 4, 5])

In [99]:
arr[np.newaxis, :]

array([[1, 2, 3, 4, 5]])

In [100]:
arr[np.newaxis, :].shape

(1, 5)

In [101]:
arr[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [102]:
arr[None, :]

array([[1, 2, 3, 4, 5]])

In [103]:
arr[:, None]

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [104]:
arr.reshape((5, 1))

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [105]:
arr_n = np.ones((3, 4, 5))
arr_n

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [106]:
arr_n.reshape(5, -1, 2)

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

### Array Concatenation and Splitting


### Concatenation



In [107]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([4, 3, 2, 1])
np.concatenate([arr1, arr2])

array([1, 2, 3, 4, 4, 3, 2, 1])

In [108]:
arr3 = [42, 42, 42, 42]
np.concatenate([arr1, arr2, arr3])

array([ 1,  2,  3,  4,  4,  3,  2,  1, 42, 42, 42, 42])

In [109]:
grid = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8]])  # axis=0

In [110]:
np.concatenate([grid, grid])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [111]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8]])

In [112]:
arr = np.array([42, 42, 42, 42])
grid = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8]])

# v
print(np.vstack([arr, grid]))

# h
# but firstly:
print(arr.reshape(2, -1))

print(np.hstack([grid, arr.reshape(2, -1)]))


# d - np.dstack - along the 3d axis.

[[42 42 42 42]
 [ 1  2  3  4]
 [ 5  6  7  8]]
[[42 42]
 [42 42]]
[[ 1  2  3  4 42 42]
 [ 5  6  7  8 42 42]]


### Splitting


In [113]:
arr = np.arange(12)
arr1, arr2, arr3, arr4 = np.split(arr, [1, 4, 10])  # N split-points to N + 1 subarrays
print(arr1, arr2, arr3, arr4, sep='\n')  

# np.hsplit
# np.vsplit

[0]
[1 2 3]
[4 5 6 7 8 9]
[10 11]


In [116]:
x = np.arange(13)
np.array_split(x, 3)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

## Universal Functions

In [117]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [118]:
x = np.arange(9).reshape((3, 3))
print(x)
2 ** x

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

### Array arithmetic


In [119]:
x = np.arange(4)
print("x      =", x)
print("-x     =", -x)
print("x + 5  =", x + 5)
print("x - 5  =", x - 5)
print("x * 2  =", x * 2)
print("x / 2  =", x / 2)
print("x // 2 =", x // 2)  # floor division
print("x ** 2 =", x ** 2)
print("x % 2  =", x % 2)
print("~x     =", ~x)

x      = [0 1 2 3]
-x     = [ 0 -1 -2 -3]
x + 5  = [5 6 7 8]
x - 5  = [-5 -4 -3 -2]
x * 2  = [0 2 4 6]
x / 2  = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
x ** 2 = [0 1 4 9]
x % 2  = [0 1 0 1]
~x     = [-1 -2 -3 -4]


In [120]:
np.add(x, 2)

array([2, 3, 4, 5])

The following table lists the arithmetic operators implemented in NumPy:

| Operator	    | Equivalent ufunc    | Description                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Addition (e.g., ``1 + 1 = 2``)         |
|``-``          |``np.subtract``      |Subtraction (e.g., ``3 - 2 = 1``)      |
|``-``          |``np.negative``      |Unary negation (e.g., ``-2``)          |
|``*``          |``np.multiply``      |Multiplication (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``        |Division (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``  |Floor division (e.g., ``3 // 2 = 1``)  |
|``**``         |``np.power``         |Exponentiation (e.g., ``2 ** 3 = 8``)  |
|``%``          |``np.mod``           |Modulus/remainder (e.g., ``9 % 4 = 1``)|


In [123]:
arr = np.array([-42, -1, 0, -3.141592, 42])
np.absolute(arr)
theta = np.linspace(0, np.pi, 3)  # trigonometric functions
print("theta       = ", theta)
print("sin(theta)  = ", np.sin(theta))
print("cos(theta)  = ", np.cos(theta))
print("tan(theta)  = ", np.tan(theta))
arr = np.linspace(-1, 1, 3)  
print("arr         = ", arr)
print("arcsin(arr) = ", np.arcsin(arr))
print("arccos(arr) = ", np.arccos(arr))
print("arctan(arr) = ", np.arctan(arr))
arr = [0, 1, 2, 3]                # exp
print("arr         =", arr)
print("e^arr       =", np.exp(arr))
print("2^arr       =", np.exp2(arr))
print("3^arr       =", np.power(3, arr))
arr = [1, 2, 4, 10]               # log
print("arr         =", arr)
print("ln(arr)     =", np.log(arr))
print("log2(arr)   =", np.log2(arr))
print("log10(arr)  =", np.log10(arr))
x = [0, 0.001, 0.01, 0.1]         # for small values
print("exp(x) - 1  =", np.expm1(x))
print("log(1 + x)  =", np.log1p(x))

theta       =  [0.         1.57079633 3.14159265]
sin(theta)  =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta)  =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta)  =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
arr         =  [-1.  0.  1.]
arcsin(arr) =  [-1.57079633  0.          1.57079633]
arccos(arr) =  [3.14159265 1.57079633 0.        ]
arctan(arr) =  [-0.78539816  0.          0.78539816]
arr         = [0, 1, 2, 3]
e^arr       = [ 1.          2.71828183  7.3890561  20.08553692]
2^arr       = [1. 2. 4. 8.]
3^arr       = [ 1  3  9 27]
arr         = [1, 2, 4, 10]
ln(arr)     = [0.         0.69314718 1.38629436 2.30258509]
log2(arr)   = [0.         1.         2.         3.32192809]
log10(arr)  = [0.         0.30103    0.60205999 1.        ]
exp(x) - 1  = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x)  = [0.         0.0009995  0.00995033 0.09531018]


## Broadcasting

https://numpy.org/doc/stable/user/basics.broadcasting.html

In [124]:
a = np.arange(3)
print(a)
b = np.array([5, 5, 5])
a + b

[0 1 2]


array([5, 6, 7])

In [125]:
a + 5

array([5, 6, 7])

In [126]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [127]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [128]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)

print(a)
print(b)

[[0]
 [1]
 [2]]
[0 1 2]


In [129]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

![Broadcasting Visual](https://www.kukuxiaai.com/images/blog/tensorflow/course/broadcasting.png)

### Rules of Broadcasting

Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:

- Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is *padded* with ones on its leading (left) side.
- Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
- Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [130]:
a = np.arange(3)
a + 5

array([5, 6, 7])

a.shape = (3,)

5.shape = (,) --> (1,) --> (3,)

In [131]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
print(a)
print(b)
a + b

[[0]
 [1]
 [2]]
[0 1 2]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

a.shape = (3, 1)          --> (3, 3)

b.shape = (3,) --> (1, 3) --> (3, 3)

In [ ]:
# 3, 3
#    3

## Aggregation 

<img src="aggregations.png" width=600px>

In [132]:
import random

In [133]:
data = [random.random() for _ in range(10_000_000)]
%timeit min(data)

195 ms ± 11.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [134]:
np_data = np.array(data)
%timeit np.min(np_data)

34.1 ms ± 2.79 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Masking

In [135]:
a = np.arange(8) ** 2
a[a > 8]

array([ 9, 16, 25, 36, 49])

In [136]:
a > 8

array([False, False, False,  True,  True,  True,  True,  True])

In [137]:
a = np.arange(4) * 2
print(a)
a[[3, 3, 2, 2, 0, 0, 1, 1]]

[0 2 4 6]


array([6, 6, 4, 4, 0, 0, 2, 2])

In [ ]:
np.ix_()